# Generated by Django 3.1.1 on 2020-10-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='isReserved',
            field=models.BooleanField(default=False),
        ),
    ]
