# Generated by Django 3.1.1 on 2020-10-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_seat_isreserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='code',
            field=models.CharField(default='AIW', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='seats',
            field=models.ManyToManyField(blank=True, related_name='movie', to='reservations.Seat'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='corMovie',
            field=models.CharField(max_length=3),
        ),
    ]
