# Generated by Django 3.1.1 on 2020-10-10 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20201010_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='seats',
        ),
        migrations.AlterField(
            model_name='seat',
            name='corMovie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='reservations.movie'),
        ),
    ]
