# Generated by Django 3.1.1 on 2020-10-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20201010_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='code',
        ),
        migrations.AddField(
            model_name='movie',
            name='seats',
            field=models.ManyToManyField(blank=True, related_name='corrMovie', to='reservations.Seat'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='corMovie',
            field=models.CharField(max_length=3),
        ),
    ]
