# Generated by Django 3.1.1 on 2020-10-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20201010_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='code',
            field=models.CharField(default='AIW', max_length=3),
            preserve_default=False,
        ),
    ]
