# Generated by Django 3.1.1 on 2020-10-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_auto_20201010_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='code',
        ),
    ]
