# Generated by Django 3.1.1 on 2020-10-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_remove_movie_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='isSelected',
            field=models.BooleanField(default=False),
        ),
    ]
